### ISSUE TITLE
Examples that still need small data:

### ISSUE THREAD

**Issue by jsignell** [pyviz-topics/examples#12]
- [x] census
 - [x] gerrymandering
 - [x] bay_trimesh
...

**Comment by jbednar** [comment]
For bay_trimesh, I think we already discussed how to do that by editing the text file.

For census, you can sample 5000 points (or whatever seems like a good balance between size and having anything recognizable at all) and write the result as a Parquet file.  I think you'll need to update the spatial indexing, as described in http://datashader.org/user_guide/2_Points.html .

For gerrymandering, you'll need the small census file and then perhaps a small version of the shapes file can be made using just Houston districts?  I would hope that's simple in GeoPandas but haven't tried it.

**Comment by jbednar** [comment]
BTW, https://anaconda.org/jbednar/census_datasizes/notebook shows a 5000-point version of census, which is definitely recognizable; not sure whether it's worth going smaller to make the data file smaller and the tests faster.
