### ISSUE TITLE
No plotting class for Dataset found

### ISSUE THREAD

**Issue by gsakkis** [pyviz-topics/examples#146]
The [NYC taxi - nongeo](https://github.com/pyviz-topics/examples/blob/master/nyc_taxi/nyc_taxi-nongeo.ipynb) notebook gives the following error in the last cell:
```
No plotting class for Dataset found
:DynamicMap   []
   :Dataset   [fare_amount]
```

versions:
- holoviews: 1.14.3
- datashader: 0.12.1

**Comment by ablythed** [comment]
Fixed in #167.
