### ISSUE TITLE
Param warnings in Boids example

### ISSUE THREAD

**Issue by ablythed** [pyviz-topics/examples#154]
When I try to run the live boids example, I see all these warnings:
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/71657990/121916478-2d62a400-cd02-11eb-90e7-a3be5a960b04.png">

**Comment by jlstevens** [comment]
Thanks for reporting this!

I recently updated this project but I may have forgotten to update the live deployment.

**Comment by jlstevens** [comment]
I've just redeployed and checked there are no more warnings.
