### ISSUE TITLE
Set up binder

### ISSUE THREAD

**Issue by jsignell** [pyviz-topics/examples#24]
There should be a top level environment.yml that can be used to create a master environment with all the necessary packages to run any of the notebooks.

There also needs to be a data acquisition mechanism. I'm wondering if we should maybe copy over the test data (`doit small_data_setup` - we'd need to extend this command to do all the projects if no project name is specified) and only really have people use that for playing with the projects in binder. The test data should be representative of the general data, but it won't be terribly impressive so if we do that we need to have a loud disclaimer telling people to pull the project down locally to use with full data, or pointing them to topics that use generated data.

**Comment by jbednar** [comment]
Will a union environment take too long to be initialized in binder for that to be practical? Or is the built environment cached?

**Comment by jbednar** [comment]
Well, not all projects use large data, so there should be plenty that would be fully usable in binder.   I guess if there is a saved image, it can't be saved with the data already in it?

**Comment by jsignell** [comment]
The built environment is cached. So we'll just need to make sure to rebuild the image any time something changes. Regarding data, there are ways to get data into binder images, but they don't want more than a could hundred MBs in an image https://github.com/binder-examples/getting-data. I guess intake would be good for the binder case. Because then people can only download as needed

**Comment by jbednar** [comment]
Ok. I don't think we should primarily be focusing on binder support; individual projects should be set up as most appropriate for each one.  So if it's using intake or it's using small files, it will work well with binder; the rest won't be that useful in that case.
