### ISSUE TITLE
Remove requirement for old tornado

### ISSUE THREAD

**Issue by jlstevens** [pyviz-topics/examples#40]
Running `anaconda project run` in `examples/nyc_taxi`:

```
anaconda-project run
Potential issues with this project:
  * anaconda-project.yml: Unknown field name 'maintainers'
  * anaconda-project.yml: Unknown field name 'dependencies'

Error downloading https://s3.amazonaws.com/datashader-data/nyc_taxi_wide.parq: initialize() got an unexpected keyword argument 'io_loop'
missing requirement to run this project: NYC Taxi Data
  Environment variable DATA is not set.
(Use Ctrl+C to quit.)
Value for DATA:
```

Potentially due to lack of tornado pinning? The URL is fine as I used `wget` to grab it...

**Comment by jbednar** [comment]
I have the same problem, with tornado=5.1.1 and tornado=6.0.2, so I don't think it's a tornado issue.

**Comment by jsignell** [comment]
It seems likely that the data dir isn't being created in time to nest the data in it.

**Comment by jbednar** [comment]
https://stackoverflow.com/questions/48090119/jupyter-notebook-typeerror-init-got-an-unexpected-keyword-argument-io-l

**Comment by jsignell** [comment]
oh https://examples.pyviz.org/getting_started.html#run-locally I have that in the instructions

**Comment by jsignell** [comment]
Works for me locally and is documented.

**Comment by jbednar** [comment]
I've re-opened this because we should really fix anaconda-project (presumably?) depending on such an old version of tornado; asking people to downgrade that to use our tools is not ideal...

**Comment by jsignell** [comment]
It is already fixed, just not released and not on AE.

**Comment by jbednar** [comment]
Ok, let's close this when it's actually available for users. Presumably we don't have to worry specifically about AE; either they install matching anaconda-project and tornado versions already, or nothing would work for them?

**Comment by jsignell** [comment]
True.
