### ISSUE TITLE
Should notebooks be executed before they are uploaded to AE?

### ISSUE THREAD

**Issue by jsignell** [pyviz-topics/examples#5]
When setting up a deployed example on AE should the notebooks be executed before they are uploaded, or can the deployment be setup to run all the cells in the notebook before finishing?

**Comment by jbednar** [comment]
I'm not sure what you mean.  If it's something to be run with `panel serve`, the notebook outputs will be ignored; it essentially just runs the .ipynb as .py, where outputs are irrelevant.  Or are you asking about a different scenario?

**Comment by jsignell** [comment]
I am asking about deploying notebooks as notebooks not as apps. This is for the case where the example isn't panel-related. For example see https://attractors-python36.aip.anaconda.com/

**Comment by jbednar** [comment]
Ah, I see.  In most cases the examples don't need to deploy at all; they can simply be static web pages as part of a pyviz-topics website. That attractors example is a special case of mixing interactive code with lots of static text and images, which is probably a bad idea -- instead we should probably pull out the interactive bits as a separate app in the same project directory, to make it clear what's static and what's not.

In any case yes, in the (presumably rare) case when we want to deploy a notebook *as a notebook*, then I agree it probably needs output included before the user sees it.

**Comment by jsignell** [comment]
Ok so the consensus is that we should not check in or upload evaluated notebooks. Most of the time we won't be deploying notebooks anyways, but when we do, it would be ideal if we could start the notebook kernel and run the notebook when the user enters the notebook. This would be implemented as a new argument in anaconda-project. https://github.com/Anaconda-Platform/anaconda-project/issues/198
