### ISSUE TITLE
Show which projects use only packages from defaults

### ISSUE THREAD

**Issue by jsignell** [pyviz-topics/examples#50]
There has been a discussion around how to expose which projects work with only the defaults channel. 

This work has two parts:
1) Going through the projects in this repo and removing the pyviz channel dependency to see whether they can build with just defaults (estimate 2 days).

2) Displaying that in the static version of the site. 
  
      a. I think the right way of doing that would be to implement a labelling system which would then show up on the gallery page or generate new gallery pages for each label. This would requite changes in nbsite and making nbsite aware of anaconda-project.yml in a way that it isn't yet. But it would also allow us to label projects with 'datashader' or 'geoviews' which serves our long-term goals (estimate 4 days).

     b. Instead of implementing the label system, we could cheat and make a .rst with static links to the right gallery assets (estimate 1 day).

**Comment by jbednar** [comment]
I vote for 1 at least.  Would it be hard to have a status page like http://status.pyviz.org that lists the channels required for each deployment?  Is that easier or harder than 2a?

**Comment by jsignell** [comment]
> Would it be hard to have a status page like http://status.pyviz.org that lists the channels required for each deployment?

I think that is about as hard as 2a without the extensibility.

**Comment by jbednar** [comment]
Ok, then I vote for 2a, because the .rst one will be too hard for us to maintain.
