### ISSUE TITLE
Should examples have versions?

### ISSUE THREAD

**Issue by jsignell** [pyviz-topics/examples#6]
It could be useful to have examples have versions, this would be most useful if we could upload revisions directly to AE.

**Comment by jlstevens** [comment]
This does make sense to me. Maybe a field declared in the anaconda-project.yml?

**Comment by jbednar** [comment]
Personally, I'd rather versions auto-increment in AE5; seems like we'd forever be chasing the .yml if versions are specified there (failing to update it, and thus deploying things that falsely claim to be an older version)...

**Comment by jbednar** [comment]
It seems like examples can simply inherit the version SHA of this repository.  E.g. currently all projects have version "bf91ecdf".  Is the idea that we should have a numeric, monotonic version number like 1.1, 1.2, etc.?  If so, I guess we could provide that by counting commits for that project directory and providing a service that will return a .zip file of the specified version from history, with the most recent commit being the one returned by default.  Doable, but I'll close this for now as not currently needed.
