### ISSUE TITLE
Add support for index notebooks as group overviews

### ISSUE THREAD

**Issue by jlstevens** [pyviz-topics/examples#68]
[examples.pyviz.org](http://examples.pyviz.org) already supports having groups of notebooks under one heading such as the three attractors notebooks:

![image](https://user-images.githubusercontent.com/890576/67015458-2eba7400-f0bc-11e9-8a08-0c0579582bc4.png)

This is already great but with one small feature we could allow these groups to act as mini examples of the dedicated topics websites (e.g [earthsim](http://earthsim.pyviz.org/) or [earthml](http://earthml.pyviz.org/)). In the description (e.g 'Calculate and plot 2d attractors of various types' above), it would be very nice if we could put a link on that visits an `index.ipynb` (or `overview.ipynb` or similar). 

This index notebook would help provide an overview of the group and help people visit the notebooks in the group in an appropriate order. The idea is that with by adding a bit of scaffolding and context around the whole group of notebooks (which can obviously still crosslink between each other), the topic becomes more of a cohesive unit just like [earthsim](http://earthsim.pyviz.org/) and [earthml](http://earthml.pyviz.org/)) (though without Tutorial and FAQ sections).

Then [examples.pyviz.org](http://examples.pyviz.org) can serve the purpose of presenting isolated topic notebooks, disjointed topic notebooks that are in the same domain but without any meaningful story to link them as well as more cohesive sections that someone interested in  a particular domain can work through in a well defined order.

Hope that makes sense!

**Comment by jbednar** [comment]
I think this would be a useful capability.

**Comment by jsignell** [comment]
I think that the concept of "an appropriate order" doesn't really align with the notion of topics, but I don't have a strong feeling either way. I would like to note though that each of these sections represents one project at the moment. If we want to change that there will need to be some tweaking of the general structure.

**Comment by jsignell** [comment]
But I don't think that the various topics under earthmsim or earthml share a datafile. Maybe I am misunderstanding the proposal. Is it just to add an index? Or is it to have grouping such as earthsim and earthml?

**Comment by jlstevens** [comment]
My thinking is that it would be nice to have an index per project and nothing more required.

**Comment by jsignell** [comment]
Would you want the others to be in the order found in the index? I think that would be kind of tricky.

**Comment by jbednar** [comment]
I think that respecting the order in the index.ipynb is indeed too tricky, as it would have to assume a very constrained format for the index.ipynb. 

Note that this proposal doesn't allow us to eliminate EarthML or EarthSim; it just fills in a gap.  I'm thinking of it as a continuum like this:

1. individual .ipynb and no dependencies]
2. anaconda project with one .ipynb and an environment
3. anaconda project with multiple .ipynbs and an environment
4. anaconda project with multiple ipynbs, an environment, and an index that organizes it all
5. separate github repo with arbitrarily many environments and .ipynbs and potentially its own Python module (like EarthSim and EarthML)

nbviewer and anaconda.org already handle 1, examples.pyviz.org already handles 2 and 3, and github handles 5.  This proposal lets examples.pyviz.org handle case 4, i.e. somewhat bigger than case 3, but not so big that it needs its own repository, its own issue trackers, its own dedicated website, etc.  It's a low-cost approximation to case 5, much  more lightweight, but still sharing the property that there can be an index that organizes and explains a set of interrelated items.

**Comment by jsignell** [comment]
I have been thinking about this more since I am setting up a mechanism to allow notebooks to be skipped. Where would the index be linked from? Would it be enough to include a link to the index in the description of the project?

**Comment by jbednar** [comment]
Sure.

**Comment by jsignell** [comment]
I spoke with @jlstevens and we decided that the whole description text can be a link to the index. I've implemented that in https://github.com/pyviz-topics/examples/pull/70.

**Comment by jsignell** [comment]
Closed in #70. Adding docs soon, but should "just work" if there is a notebook named index.ipynb.
